### ISSUE TITLE
Temp files not deleted on server

### ISSUE THREAD

**Issue by ironman1964** [webgio/Rotativa#122]
Hi,

If I create a pdf, the tempfile created in C:\Windows\Temp is not deleted.
Any change on fixing this little annoying bug ?

Thanks !

**Comment by webgio** [comment]
Hi, just found out the wkhtmltopdf testing release v0.12.3 should fix (https://github.com/wkhtmltopdf/wkhtmltopdf/blob/79ff51e/CHANGELOG.md). You could download the exe from here: http://wkhtmltopdf.org/downloads.html and replace the exe in the project Rotativa dir.

**Comment by ironman1964** [comment]
Hi @webgio,
I can't find the binaries on the download page.
Any help appreciated !

**Comment by webgio** [comment]
Download the exe and then run it, it will install on local disk, grab the wkhtmltopdf.exe file in the folder of installation.

**Comment by ironman1964** [comment]
Yeah !! It's working ... no more temp files !!

**Comment by gabrielalfa** [comment]
Hello my friend

First parebens by its rotating library is very useful and easy to use.

However, I have had problems with the server security levels where my application is hosted.

My server, for defaut of Micrisoft requires server levels "Meduim trust" and its application does not match these requirements.

I believe one reason for this act.

I'm sending you down the solutions of the developers of my hosting.


Some tips for adapting your application for Medium Trust, are:

 

- If you can contact the component developer, make sure it is digitally signed by a key "Strong Name." It is necessary that the attribute "AllowPartiallyTrustedCallers" is defined in the component source code as
msdn.microsoft.com/en-us/library/system.security.allowpartiallytrustedcallersattribute.aspx. Also check on all dependent components, because if any of them has the same problem, the error may be displayed on the component that called or else then request from the manufacturer a compatible version environments "partially trusted" or "medium trust".
