### ISSUE TITLE
any plan to support .net core?

### ISSUE THREAD

**Issue by DealerCorp** [webgio/Rotativa#158]

**Comment by TheSalarKhan** [comment]
Yes please that would be awesome! But I guess its going to be a bit hard because Rotativa depends upon wkhtmltopdf.exe which is dependant upon Windows VS Redistributable packages?? I hope I'm wrong and it can be ported for .NET CORE

**Comment by TheSalarKhan** [comment]
There's now a project that uses PhantomJs to generate pdf files from html strings. it can be found [here](https://github.com/TheSalarKhan/PhantomJs.NetCore). This solution works with .NET Core on Linux, and should also work on Windows and OSX. Cheers! ^_^

**Comment by rymnikski** [comment]
Hi, wkhtmltopdf exist on Linux and is executable by a .sh file. It is easy to install and configure.
I made some test with wkhtmltopdf and ASP Core to print big reports, works very well with a great performance. I suppose that will not be very hard port this library to .NET standard.

**Comment by salar-khan-symc** [comment]
@rymnikski Hi! Can you please point us to a reference implementation, or any other resource for getting kick started with it. Thanks!

**Comment by bryanllewis** [comment]
Search for "Rotativa.NetCore" on NuGet.  Works fine for me.

**Comment by snibe** [comment]
i could not get Rotativa.NetCore to work i kept getting an error about cookies authentication  any ideas?

**Comment by wlafrance** [comment]
Issue noted here...  https://github.com/webgio/Rotativa/issues/173

**Comment by webgio** [comment]
I just published Rotativa.AspNetCore. Please let me know if it works for you.
[Rotativa.AspNetCore](https://github.com/webgio/Rotativa.AspNetCore)

**Comment by snibe** [comment]
I was able to finally get it working but I think I had an issue with actionToPDF versus ViewtoPDF or what not.  It has been a while since I looked at it.  Thank you very much for your work it is such a great tool!

Billy Williams
IT Analyst III
Information Technology Services
UT Institute of Agriculture
201G McCord Hall, 2640 Morgan Circle, Knoxville, TN 37996

865-974-7330 Office / 865-974-8391 Fax
bwilli33@tennessee.edu<mailto:bwilli33@tennessee.edu> | ag.tennessee.edu/its<http://ag.tennessee.edu/its>

Welcome to this brand new day. This day has never been lived before. It’s a
blank canvas. If you will it so, it can be your masterpiece.- HHH
