### ISSUE TITLE
ActionAsPdf renders login view in pdf - Different Issue

### ISSUE THREAD

**Issue by seanstenlund** [webgio/Rotativa#57]
Had no problems until I upgraded to MVC5 using AspNet.Identity.

I can call the ActionResult and see the view with no problems. But when I call it with ActionAsPdf it renders the login view in the pdf file.

I've tried modifications to the Web.config file including changing:
    authentication mode="None"
to
    authentication mode="Forms"
and
    modules
      remove name="FormsAuthenticationModule"
    modules
to
    validation validateIntegratedModeConfiguration="false"
    modules runAllManagedModulesForAllRequests="true"
    modules
with no success.

Is Rotativa just not compatible with MVC5 yet?

**Comment by norris1976** [comment]
I have the same issue. This is NOT solved.
@webgio - any indication as to when this might be fixed?

Thanks dude!

**Comment by webgio** [comment]
I'm unable to test on mvc 5 now. Could you check what cookie is required? you can specify a different cookie with the FormsAuthenticationCookieName property.

**Comment by DavidLibido** [comment]
I solved this in the past (on MVC4) by using:
var pdf = new ActionAsPdf("Print", new { id });
pdf.FormsAuthenticationCookieName = FormsAuthentication.FormsCookieName;
Perhaps it also works using MVC5?

**Comment by janessaallen** [comment]
David, thanks for the suggestion. However, it doesn't for for MVC5. Guess I'll try the ViewAsPdf...

**Comment by marcheneli** [comment]
I have solved this problem by this way:

Dictionary<string, string> cookieCollection = new Dictionary<string, string>();

foreach (var key in Request.Cookies.AllKeys)
{
   cookieCollection.Add(key, Request.Cookies.Get(key).Value);
}

return new ActionAsPdf("ActionName")
{
  FileName = "Name.pdf",
  Cookies = cookieCollection
};

**Comment by dcalvom** [comment]
Hi,

I tried this last solution but it doesn't works for me. All of you having this problem are using Form Authentication method? I'm using Windows Authentication, and I think that this package doesn't support this type of authentication. As other i have tried ViewAsPdf with success on generating the PDF but without stylesheets and format. Did someone have founded any solution for this problem with windows authentication (active directory)?. Thanks

**Comment by kbsaravana** [comment]
yes, I'm also facing the same issue with Windows Authentication. 
any solutions for Windows Authentication?

**Comment by jsz3** [comment]
I tried several solutions to create PDF output from an ASP.NET Identity2 and found Rotativa to be the only one that would work. The View that I needed to convert requires a complex ViewModel, so I had to use "ActionAsPdf" because "ViewAsPdf" would not work. I found that unless I passed the cookieCollection as marcheneli commented, the resulting PDF was the application's Login page. Creating the PDF, which is a single page of text that has been rendered with Bootstrap panels (yes, there are colored outlines) and one relatively small graphic image, takes an incredibly LONG time on a local IIS in debug mode. 

Are there any ways to make the process go faster?

**Comment by southplatte** [comment]
Using forms authentication with Rotativa 1.6.4 via NuGet, I have tried both DavidLibido's suggestion and Marcheneli's suggestion, individually, and combined and neither work

            //build cookie dict here
            Dictionary<string, string> cookieCollection = new Dictionary<string, string>();

            foreach (var key in Request.Cookies.AllKeys)
            {
                cookieCollection.Add(key, Request.Cookies.Get(key).Value);
            }

            var pdfResult = new ActionAsPdf("Report", new {reportid = Request.Params["reportid"]});
            pdfResult.Cookies = cookieCollection;
            pdfResult.FormsAuthenticationCookieName = FormsAuthentication.FormsCookieName;
            var binary = pdfResult.BuildPdf(this.ControllerContext);
I have also tried this way

           var pdfResult = new ActionAsPdf("Report", new {reportid =                 Request.Params["reportid"]})
            {
                Cookies = cookieCollection,
                FormsAuthenticationCookieName = FormsAuthentication.FormsCookieName
            };
            var binary = pdfResult.BuildPdf(this.ControllerContext);

It passes the reportid just fine, but it creates a new anonymous web request when I call BuildPdf(this.ControllerContext), and upon inspection I can see that the cookies are part of the ActionAsPdf object, which I've named pdfResult, as well as the .ASPXAUTH cookie name being present.  So it appears they are there, but they are not being passed in properly.

Any ideas on this?  Running MVC 5, IIS 8.  When I run it I get the error: "Error: Failed loading page http://xxx.xxx.xxx.xxx/Reporting/Remarketing/RemarketingReport?reportid=cd23r4s3-da79-455d-8137-394kdie98f30 (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1, due to unknown error."  Which when I run it with this URL on the command line, I get the Login page as the pdf, so assuming it's an authentication issue related to this thread, that I have either:

A) missed the solution to
B) solution is not working
