### ISSUE TITLE
page break doesn't work with 1.6.3 + versions

### ISSUE THREAD

**Issue by patil-nileshb** [webgio/Rotativa#82]
I have multiple pages in my view & i separate them with

<div style="page-break-after:always;"></div>

which works fine with v1.6.1 but when i tried to update to v1.6.3, it didn't work. the page breaks didn't work. i even tried v1.6.4-beta but the same result.
don't know if it was change in wkhtmltopdf update

**Comment by ganeshjr** [comment]
Hi, Is this a bug that will be fixed? The table rows page break does not work for me.

Css: table.items tbody, table.items tr , table.items td{page-break-inside: avoid !important;}

I am using the latest version Rotativa 1.6.4 from nuget and copied the latest wkhtmltopdf v0.12.2.1 exe and dlls into the Rotativa folder.

Looks like wkhtmltopdf started supporting the page break for table rows and table body since v0.12.1.

Thanks,
Ganesh

**Comment by parissge** [comment]
I have the same problem also. Version 1.6.4.

**Comment by G43beli** [comment]
same issue here. I downgraded to V1.6.1 in the meantime. Is there any possibility to achieve the page-breaks in one of the newer version?

**Comment by pj6** [comment]
Still broken.

**Comment by webgio** [comment]
Updated wkhtmltopdf version to 0.12.4, please check if problem still exist.
I've published it in a new pre-release version:
`Install-Package Rotativa -Pre`
