### ISSUE TITLE
Server error in '/' application when using SSL with Rotativia ActionToPdf

### ISSUE THREAD

**Issue by stuartupton** [webgio/Rotativa#91]
We have a site set up that uses the rotativia ActionToPdf.  Printing to PDF works fine until we add an SSL to the sub domain, when we do we get the following error;

Qt: Untested Windows version 6.2 detected!
Error: Failed loading page https://oursubdomain.ourdomain.co.uk/FormInstance/Print/73951?outContent=form (sometimes it will work just to ignore this error with --load-error-handling ignore)

  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.Exception: Qt: Untested Windows version 6.2 detected!
Error: Failed loading page https://oursubdomain.ourdomain.co.uk/FormInstance/Print/73951?outContent=form (sometimes it will work just to ignore this error with --load-error-handling ignore)

Take the SSL off and it works fine again, is there something we are missing?

**Comment by BrianMinister** [comment]
Don't use SSL. Use TLS. But that doesn't solve your problem. :) 

I suspect that part of your site is still being issued through port 80. Setup a test site that runs on 443 only and see if the problem persists. I have seen cases where mixed protocols into browser callbacks have caused the server to treat the calls as cross domain.So you can try to assign cross domain acceptance for the :80 to :443 acceptance.

Since I don't see your server information, you will have to google the how to on this.
